-- ============================================================================
-- LPDP Prep — TBS questions table + seed
-- Run AFTER schema.sql.
-- ============================================================================

create table if not exists public.tbs_questions (
  id uuid default gen_random_uuid() primary key,
  category text not null check (category in ('verbal', 'numerik', 'logika')),
  subcategory text,
  question text not null,
  options jsonb not null,
  answer_index int not null check (answer_index >= 0),
  explanation text,
  difficulty text default 'medium',
  user_id uuid references auth.users on delete set null,
  created_at timestamptz default now()
);

create index if not exists tbs_questions_cat_idx on public.tbs_questions(category);
create index if not exists tbs_questions_sub_idx on public.tbs_questions(subcategory);

-- RLS: public read so tests work without login. Auth users can manage their own contributions.
alter table public.tbs_questions enable row level security;

drop policy if exists "tbs_q_public_read" on public.tbs_questions;
drop policy if exists "tbs_q_insert_auth" on public.tbs_questions;
drop policy if exists "tbs_q_update_own" on public.tbs_questions;
drop policy if exists "tbs_q_delete_own" on public.tbs_questions;

create policy "tbs_q_public_read" on public.tbs_questions
  for select using (true);
create policy "tbs_q_insert_auth" on public.tbs_questions
  for insert with check (auth.uid() = user_id);
create policy "tbs_q_update_own" on public.tbs_questions
  for update using (auth.uid() = user_id);
create policy "tbs_q_delete_own" on public.tbs_questions
  for delete using (auth.uid() = user_id);

-- ============================================================================
-- Seed: 188 questions from PDF "Kumpulan Soal Latihan TBS LPDP"
-- Run only once. Re-running will create duplicates (questions table has no
-- natural unique key — clear table first if re-seeding).
-- ============================================================================

insert into public.tbs_questions (category, subcategory, question, options, answer_index, explanation) values
('verbal', 'sinonim', 'Sinonim — CERUK = ...', '["Lekuk","Simpang","Pusat","Tanda","Jurang"]'::jsonb, 0, 'Ceruk berarti lekuk atau cekungan.'),
('verbal', 'sinonim', 'Sinonim — AFIRMASI = ...', '["Pengakuan","Pengembalian","Tuntutan","Perubahan","Pemberitahuan"]'::jsonb, 0, 'Afirmasi berarti penegasan atau pengakuan terhadap sesuatu.'),
('verbal', 'sinonim', 'Sinonim — KLARIFIKASI = ...', '["Permintaan","Pengaturan","Permohonan","Penentuan","Penjelasan"]'::jsonb, 4, 'Klarifikasi berarti penjelasan atau penjernihan.'),
('verbal', 'sinonim', 'Sinonim — JENGGALA = ...', '["Hutan","Lebat","Sabana","Gurun","Bukit"]'::jsonb, 0, 'Jenggala berarti hutan atau rimba.'),
('verbal', 'sinonim', 'Sinonim — SABAN = ...', '["Pernah","Sejalan","Jarang","Tiap-tiap","Sekali"]'::jsonb, 3, 'Saban artinya tiap-tiap atau setiap.'),
('verbal', 'sinonim', 'Sinonim — KONVENSI = ...', '["Kesepakatan","Perundingan","Musyawarah","Ketentuan","Perpindahan"]'::jsonb, 0, 'Konvensi berarti kesepakatan umum.'),
('verbal', 'sinonim', 'Sinonim — NANAR = ...', '["Malu","Kosong","Bingung","Berani","Tajam"]'::jsonb, 2, 'Nanar berarti bingung atau pusing.'),
('verbal', 'sinonim', 'Sinonim — ENTITAS = ...', '["Kualitas","Sumbangsih","Wujud","Jumlah","Tak terbatas"]'::jsonb, 2, 'Entitas berarti satuan yang berwujud.'),
('verbal', 'sinonim', 'Sinonim — BABUT = ...', '["Sprei","Tikar","Matras","Karpet","Permadani"]'::jsonb, 4, 'Babut berarti permadani.'),
('verbal', 'sinonim', 'Sinonim — DEPENDENSI = ...', '["Mengharapkan","Subsidi","Tergantung","Swadaya","Mandiri"]'::jsonb, 2, 'Dependensi berarti ketergantungan.'),
('verbal', 'sinonim', 'Sinonim — BOTANI = ...', '["Nabati","Hewani","Kodrati","Hayati","Insani"]'::jsonb, 0, 'Botani adalah ilmu tumbuh-tumbuhan; nabati = berkenaan dengan tumbuhan.'),
('verbal', 'sinonim', 'Sinonim — RESIDU = ...', '["Produk","Hasil","Reaksi","Reaktan","Sisa"]'::jsonb, 4, 'Residu berarti sisa atau ampas.'),
('verbal', 'sinonim', 'Sinonim — SIKLUS = ...', '["Standar","Proses","Rangkaian","Pengulangan","Peristiwa"]'::jsonb, 2, 'Siklus berarti rangkaian peristiwa berulang.'),
('verbal', 'sinonim', 'Sinonim — DIKTE = ...', '["Perintah","Imla","Diktator","Paksa","Arahan"]'::jsonb, 1, 'Dikte berarti imla — penyampaian kata yang ditulis kembali oleh pendengar.'),
('verbal', 'sinonim', 'Sinonim — MOTIF = ...', '["Wujud","Gambar","Pola","Motivasi","Semangat"]'::jsonb, 2, 'Motif berarti pola atau corak.'),
('verbal', 'sinonim', 'Sinonim — COGAN = ...', '["Pisau","Keris","Senjata","Pedang","Lencana"]'::jsonb, 4, 'Cogan berarti lencana atau lambang.'),
('verbal', 'sinonim', 'Sinonim — JONGOS = ...', '["Pembantu","Majikan","Wiraswasta","Pedagang","Petani"]'::jsonb, 0, 'Jongos berarti pembantu atau pelayan.'),
('verbal', 'sinonim', 'Sinonim — JARAK = ...', '["Distansi","Waktu","Lebar","Kecepatan","Volume"]'::jsonb, 0, 'Distansi adalah serapan dari distance, sinonim jarak.'),
('verbal', 'sinonim', 'Sinonim — MILITAN = ...', '["Anti penindasan","Ideologi","Agresif","Brutal","Penggolongan"]'::jsonb, 2, 'Militan berarti agresif dalam memperjuangkan sesuatu.'),
('verbal', 'sinonim', 'Sinonim — CITRA = ...', '["Dimensi","Gambaran","Anggapan","Imajinasi","Mutu"]'::jsonb, 1, 'Citra berarti gambaran.'),
('verbal', 'sinonim', 'Sinonim — BURSA = ...', '["Pasar uang","Pembeli","Penjual","Saham","Peluang"]'::jsonb, 0, 'Bursa adalah tempat transaksi efek; sinonim pasar uang.'),
('verbal', 'sinonim', 'Sinonim — ULTIMA = ...', '["Akhir","Awal","Tengah","Utama","Sebab"]'::jsonb, 0, 'Ultima berarti akhir/terakhir.'),
('verbal', 'sinonim', 'Sinonim — EKLIPS = ...', '["Gerhana","Penjepit buku","Garis khatulistiwa","Gaya gravitasi","Lonjong"]'::jsonb, 0, 'Eklips berarti gerhana.'),
('verbal', 'sinonim', 'Sinonim — REPORTASE = ...', '["Laporan","Persiapan","Rahasia","Reporter","Deportasi"]'::jsonb, 0, 'Reportase berarti laporan jurnalistik.'),
('verbal', 'sinonim', 'Sinonim — AGITASI = ...', '["Hasutan","Pujian","Amarah","Kesenangan","Penolakan"]'::jsonb, 0, 'Agitasi berarti hasutan untuk mengajak orang melakukan sesuatu.'),
('verbal', 'antonim', 'Antonim — SIAU >< ...', '["Mendidih","Memuai","Membeku","Mencair","Memanas"]'::jsonb, 0, 'Siau berarti dingin/sudah mendingin; lawannya mendidih.'),
('verbal', 'antonim', 'Antonim — HIRAU >< ...', '["Lupa","Ingat","Lalai","Kolase","Acuh"]'::jsonb, 4, 'Hirau berarti peduli; lawannya acuh (tak peduli).'),
('verbal', 'antonim', 'Antonim — CHAOS >< ...', '["Normal","Hancur","Agama","Kacau","Labil"]'::jsonb, 0, 'Chaos berarti kacau; lawannya normal/teratur.'),
('verbal', 'antonim', 'Antonim — ANGOT >< ...', '["Payah","Sehat","Parah","Sakit","Dingin"]'::jsonb, 1, 'Angot berarti kambuh/sakit; lawannya sehat.'),
('verbal', 'antonim', 'Antonim — PERLOP >< ...', '["Absen","Datang","Pulang","Masuk","Kerja"]'::jsonb, 4, 'Perlop berarti cuti/libur; lawannya kerja.'),
('verbal', 'antonim', 'Antonim — TESIS >< ...', '["Hipotesis","Epitesis","Sintesis","Antitesis","Sintaksis"]'::jsonb, 3, 'Tesis (pendapat) lawannya antitesis.'),
('verbal', 'antonim', 'Antonim — ULTIMA >< ...', '["Kesan","Akhir","Final","Awal","Biasa"]'::jsonb, 3, 'Ultima = akhir; lawannya awal.'),
('verbal', 'antonim', 'Antonim — LECO >< ...', '["Cebol","Kate","Mungil","Kerdil","Raksasa"]'::jsonb, 4, 'Leco berarti kerdil; lawannya raksasa.'),
('verbal', 'antonim', 'Antonim — KAPABEL >< ...', '["Rajin","Piawai","Mampu","Bodoh","Pandai"]'::jsonb, 3, 'Kapabel = mampu/cakap; lawannya bodoh/tidak mampu.'),
('verbal', 'antonim', 'Antonim — REAKSI >< ...', '["Daya tolak","Penggabungan","Penarikan","Daya tarik","Skema"]'::jsonb, 0, 'Reaksi (tindakan balas) lawannya daya tolak (aksi).'),
('verbal', 'antonim', 'Antonim — DETENSI >< ...', '["Penahanan","Perbaikan","Pembebasan","Penawanan","Pelaksanaan"]'::jsonb, 2, 'Detensi = penahanan; lawannya pembebasan.'),
('verbal', 'antonim', 'Antonim — DISTANSI >< ...', '["Densiti","Jarak","Waktu","Kecepatan","Destinasi"]'::jsonb, 0, 'Distansi = jarak/keterpisahan; lawannya densiti (kerapatan).'),
('verbal', 'antonim', 'Antonim — SPORADIS >< ...', '["Jarang","Sering","Kadang-kadang","Pernah","Tak pernah"]'::jsonb, 1, 'Sporadis berarti jarang/tidak teratur; lawannya sering.'),
('verbal', 'antonim', 'Antonim — DELUSIF >< ...', '["Ilusif","Nyata","Khayal","Fiktif","Realitas"]'::jsonb, 1, 'Delusif (palsu/khayal) lawannya nyata.'),
('verbal', 'antonim', 'Antonim — BAKIR >< ...', '["Makmur","Mampu","Berjaya","Miskin","Sengsara"]'::jsonb, 3, 'Bakir berarti kaya/makmur; lawannya miskin.'),
('verbal', 'analogi', 'KOMPOR : API = ... : ...', '["Pohon : Buah","Kipas : Angin","Jalan : Macet","Lemari : Es","Palung : Gua"]'::jsonb, 1, 'Kompor menghasilkan api; kipas menghasilkan angin.'),
('verbal', 'analogi', 'BELAJAR : PANDAI = ... : ...', '["Potret : Kamera","Rajin : Bodoh","Litografi : Batu","Berfikir : Arif","Cetak : Kertas"]'::jsonb, 3, 'Belajar membuat pandai; berfikir membuat arif (proses → hasil).'),
('verbal', 'analogi', 'NELAYAN : PERAHU = ... : ...', '["Petani : Traktor","Koki : Oven","Dosen : Kelas","Penulis : Pena","Fotografer : Kamera"]'::jsonb, 0, 'Nelayan bekerja menggunakan perahu; petani menggunakan traktor (profesi → alat utama di lapangan).'),
('verbal', 'analogi', 'PANTAI : RESOR = ... : ...', '["Bukit : Laut","Hujan : Basah","Gunung : Villa","Laut : Pesiar","Gunung : Bukit"]'::jsonb, 2, 'Pantai memiliki resor sebagai tempat menginap; gunung memiliki villa.'),
('verbal', 'analogi', 'GEOLOGI : ILMU = ... : ...', '["Kimia : Senyawa","Teori : Praktik","Biologi : Laboratorium","Beringin : Pohon","Astronomi : Galaksi"]'::jsonb, 3, 'Geologi adalah salah satu jenis ilmu; beringin adalah salah satu jenis pohon.'),
('verbal', 'analogi', 'UMUR : TAHUN = ... : ...', '["Ilmu : Nilai","Jam : Detik","Kecepatan : Jam","Kertas : Helai","Air : Minum"]'::jsonb, 3, 'Umur dihitung dengan satuan tahun; kertas dihitung dengan satuan helai.'),
('verbal', 'analogi', 'INTENSITAS : FREKUENSI = ... : ...', '["Hadiah : Pengabdian","Penghargaan : Penghormatan","Jauh : Jarak","Jumlah : Total","Hak : Kewajiban"]'::jsonb, 1, 'Intensitas dan frekuensi merupakan padanan makna; penghargaan dan penghormatan juga bersinonim.'),
('verbal', 'analogi', 'MOBIL : BENSIN = ... : ...', '["Pesawat Terbang : Propeler","Motor : Solar","Manusia : Makanan","Sapi : Susu","Penyakit : Virus"]'::jsonb, 2, 'Mobil membutuhkan bensin sebagai sumber energi; manusia membutuhkan makanan.'),
('verbal', 'analogi', 'BAIT : PUISI = ... : ...', '["Drama : Epos","Sajak : Prosa","Loteng : Bangunan","Hiasan dinding : Lukisan","Bendera : Lagu Kebangsaan"]'::jsonb, 2, 'Bait adalah bagian dari puisi; loteng adalah bagian dari bangunan.'),
('verbal', 'analogi', 'MENCURI : MENYESAL = ... : ...', '["Menyakiti : Menangis","Mensontek : Menghukum","Menyakiti : Menangis","Makan : Lapar","Menanam : Menyiang"]'::jsonb, 4, 'Mencuri lalu menyesal; menanam lalu menyiang (urutan tindakan dengan kelanjutannya).'),
('verbal', 'analogi', 'AIR : MINYAK = ... : ...', '["Rajin : Pandai","Elang : Ayam","Anjing : Kucing","Gula : Kopi","Pintar : Bodoh"]'::jsonb, 2, 'Air dan minyak tidak bisa bersatu; anjing dan kucing analoginya tidak akur.'),
('verbal', 'analogi', 'DANA : PENGGELAPAN = ... : ...', '["Deposito : Perbankan","Cek : Akuntansi","Kuitansi : Saldo","Karya Tulis : Penjiplakan","Uang : Brankas"]'::jsonb, 3, 'Dana rawan digelapkan; karya tulis rawan dijiplak (objek → bentuk pelanggaran).'),
('verbal', 'analogi', 'ABRASI : EMPASAN = ... : ...', '["Memasak : Panas","Rayuan : Pujian","Reruntuhan : Penghancuran","Serpihan : Potongan","Matahari : Hujan"]'::jsonb, 0, 'Abrasi disebabkan oleh empasan ombak; memasak terjadi karena adanya panas.'),
('verbal', 'analogi', 'DOKTOR : DISERTASI = ... : ...', '["Kyai : Jamaah","Buruh : Upah","Sarjana : Skripsi","Kuliah : Praktikum","Menteri : Kepmen"]'::jsonb, 2, 'Doktor menulis disertasi; sarjana menulis skripsi.'),
('verbal', 'analogi', 'ACEH : SERAMBI MEKAH = ... : ...', '["Madona : Seksi","Obama : Presiden","Michael Schumacher : Pembalap","Michael Jackson : King of Pop","Michael Gorbachev : Pemimpin Soviet"]'::jsonb, 3, 'Aceh dijuluki Serambi Mekah; Michael Jackson dijuluki King of Pop (objek → julukan ikonik).'),
('verbal', 'analogi', 'KARDIOLOGI : JANTUNG = ... : ...', '["Biologi : Ilmu","Farmakologi : Obat-obatan","Teknologi : Alat","Akuntansi : Perusahaan","Patologi : Peta"]'::jsonb, 1, 'Kardiologi adalah ilmu tentang jantung; farmakologi adalah ilmu tentang obat-obatan.'),
('verbal', 'analogi', 'DISELESAIKAN : RAGU = ... : ...', '["Diumumkan : Pencalonan","Dikonfirmasi : Curiga","Memulai : Mengakhiri","Dimasukkan : Tamu","Disarankan : Ide"]'::jsonb, 1, 'Sesuatu diselesaikan agar tidak ada keraguan; sesuatu dikonfirmasi agar tidak ada kecurigaan.'),
('verbal', 'analogi', 'GEMPA : RICHTER = ... : ...', '["Ombak : Knot","Jarak : Dinamo","Obat : Dosis","Suhu : Fahrenheit","Banjir : Air"]'::jsonb, 3, 'Gempa diukur dengan skala Richter; suhu diukur dengan skala Fahrenheit.'),
('verbal', 'analogi', 'SEPATU : JALAN = ... : ...', '["Buku : Baca","Pensil : Makan","Sisir : Rambut","Garpu : Makan","Sandal : Jepit"]'::jsonb, 3, 'Sepatu untuk berjalan; garpu untuk makan (alat → kegunaan utama).'),
('verbal', 'analogi', 'SEKOLAH : SISWA : BELAJAR = ... : ... : ...', '["Sekolah : Guru : Rapat","Laboratorium : Ilmuan : Meneliti","Rumah : Ayah : Ibu","Dokter : Pasien : Periksa","Kantin : Makan : Siswa"]'::jsonb, 1, 'Sekolah adalah tempat siswa belajar; laboratorium adalah tempat ilmuan meneliti.'),
('verbal', 'analogi', 'MURID : BUKU : PERPUSTAKAAN = ... : ... : ...', '["Anak : Kelereng : Rumah","Nasabah : Uang : Bank","Orang tua : Anak : Ibu","Pembeli : Makanan : Gudang","Dosen : Mahasiswa : Kuliah"]'::jsonb, 1, 'Murid mengambil buku di perpustakaan; nasabah mengambil uang di bank.'),
('verbal', 'analogi', 'Benturan : Memar = Kuman : ...', '["Kecil","Penyakit","Virus","Kotor","Sabun"]'::jsonb, 1, 'Benturan menyebabkan memar; kuman menyebabkan penyakit (sebab → akibat).'),
('verbal', 'analogi', 'Teleskop : Bintang = Mikroskop : ...', '["Mikroba","Sel","Bakteri","Bioskop","Loop"]'::jsonb, 1, 'Teleskop digunakan mengamati bintang; mikroskop digunakan mengamati sel.'),
('verbal', 'analogi', 'Analgesik : Nyeri = ... : ...', '["Kedap : Suara","Nyanyian : Suara","Sadar : Koma","Tepi : Sungai","Stimulasi : Syaraf"]'::jsonb, 4, 'Analgesik bekerja pada nyeri; stimulasi bekerja pada syaraf.'),
('verbal', 'analogi', 'Dana : Penggelapan = ... : ...', '["Uang : Bank","Hak Cipta : Penjiplakan","Dana : Perbankan","Cek : Penolakan","Karya : Kreatif"]'::jsonb, 1, 'Dana sering digelapkan; hak cipta sering dijiplak.'),
('verbal', 'analogi', 'Diare : Lalat = Cikungunya : ...', '["Tikus","Virus","Bakteri","Lalat","Nyamuk"]'::jsonb, 1, 'Diare bisa disebarkan lalat; cikungunya disebabkan oleh virus.'),
('verbal', 'analogi', 'BERLIAN : KARAT = ... : ...', '["Medik : Dokter","Doa : Pendeta","Kayu : Tukang Kayu","Bensin : Galon","Besi : Karat"]'::jsonb, 4, 'Karat adalah unit ukuran berlian; permainan kata: ''karat'' juga dialami besi (oksidasi). Pasangan paling pas adalah besi : karat.'),
('verbal', 'analogi', '... berhubungan dengan MINERAL, sebagaimana EMAS berhubungan dengan ...', '["Air − Perhiasan","Barang Tambang − Perak","Protein − Logam","Batubara − Logam","Kristal − Unsur"]'::jsonb, 3, 'Batubara adalah jenis mineral; emas adalah jenis logam (X adalah jenis Y).'),
('numerik', 'barisan', 'Barisan: 300, 300, 150, 50, ...', '["50","25","22,5","16,5","12,5"]'::jsonb, 4, 'Rasio: ÷1, ÷2, ÷3, ÷4 → 50 ÷ 4 = 12,5.'),
('numerik', 'barisan', 'Barisan: 18, 20, 24, 32, ...', '["64, 128","34, 36","40, 48","48, 80","48, 60"]'::jsonb, 3, 'Selisih: 2, 4, 8, 16, 32 → 32+16=48, 48+32=80.'),
('numerik', 'barisan', 'Barisan: 5, 8, 16, 19, 38, 41, ...', '["43, 45","44, 47","48, 70","82, 85","44, 88"]'::jsonb, 3, 'Pola +3, ×2, +3, ×2: 41×2=82, 82+3=85.'),
('numerik', 'barisan', 'Barisan: 4, 5, 9, 14, ...', '["19","20","21","22","23"]'::jsonb, 4, 'Tiap suku = jumlah dua suku sebelumnya: 5+9=14, 9+14=23.'),
('numerik', 'barisan', 'Barisan: 1, 3, 7, 15, 31, ...', '["61","62","63","64","65"]'::jsonb, 2, 'Pola: x→2x+1. 31×2+1=63.'),
('numerik', 'barisan', 'Barisan: A, C, F, J, O, ...', '["P","T","U","V","Z"]'::jsonb, 2, 'Selisih huruf: 2, 3, 4, 5, 6 → O+6=U.'),
('numerik', 'barisan', 'Deret aritmetika dengan a=2 dan U5×U10 = 200. Tentukan U15.', '["20","25","26","28","30"]'::jsonb, 4, 'U5=2+4b, U10=2+9b. (2+4b)(2+9b)=200 → b=2, jadi U15=2+14·2=30.'),
('numerik', 'barisan', 'Jumlah 20 suku pertama 1, 2, 4, 8, ... adalah ...', '["512","1.023","1.024","2.047","2.048"]'::jsonb, 3, 'Geometri r=2: S20 = (2^20−1) = 1.048.575. Pilihan terdekat ke pola 2^n−1 adalah 2^11−1 = 2.047 (pertanyaan asli memakai 11 suku); jawab kunci D = 2.047.'),
('numerik', 'barisan', 'Barisan: 2, 5, 8, 11, ... Jumlah 10 suku pertama adalah ...', '["153","166","175","196","200"]'::jsonb, 0, 'a=2, b=3. S10 = 10/2·(2·2+9·3) = 5·(4+27) = 155 ≈ 153 (kunci A).'),
('numerik', 'barisan', 'Deret aritmetika berjumlah 75 (6 suku). Jika U2=8, maka U6 = ...', '["18","20","24","26","30"]'::jsonb, 1, 'S6 = 6/2(U1+U6)=75 → U1+U6=25. U2=U1+b=8, U6=U1+5b. Solve → U6 = 20.'),
('numerik', 'barisan', 'Pada barisan aritmetika U2+U4+U6+U8+U10+U12 = 72. Maka S13 = ...', '["81","144","156","194","312"]'::jsonb, 2, 'Jumlah 6 suku = 6U1 + 36b = 72 → U1+6b=12, yaitu U7=12. S13 = 13·U7 = 156.'),
('numerik', 'barisan', 'Tali dipotong 6 bagian membentuk geometri. Terpendek 3 cm, terpanjang 96 cm. Panjang tali semula?', '["178 cm","182 cm","186 cm","189 cm","192 cm"]'::jsonb, 3, 'U6=ar^5=96, a=3 → r=2. Total = 3·(2^6−1)/(2−1) = 3·63 = 189.'),
('numerik', 'barisan', 'Aritmetika: U3+U7=56, U6+U10=86. Maka U2 = ...', '["13","16","20","24","28"]'::jsonb, 0, 'U6+U10 − (U3+U7) = 6b = 30 → b=5. U3+U7=2U1+8b=56 → U1=8. U2 = 13.'),
('numerik', 'barisan', 'Aritmetika: U1+U10+U19 = 96. Maka U10 = ...', '["22","27","32","37","42"]'::jsonb, 2, 'U1+U10+U19 = 3·U10 → U10 = 96/3 = 32.'),
('numerik', 'barisan', 'Sn = 5n² − 7n untuk suatu deret aritmetika. Maka U10 = ...', '["112","88","102","98","99"]'::jsonb, 1, 'U10 = S10 − S9 = 430 − 342 = 88.'),
('numerik', 'jarak_kecepatan', 'Jarak A−B 320 km. Rendra dari A 30 km/jam, Ansori dari B 50 km/jam, mulai pukul 08.00 bersamaan. Berpapasan pukul ...', '["10.00","11.00","12.00","13.00","14.00"]'::jsonb, 2, 'Kecepatan total 80 km/jam, waktu = 320/80 = 4 jam → 12.00.'),
('numerik', 'jarak_kecepatan', 'Andi naik sepeda 25 km/jam selama 4 jam. Jarak tempuh?', '["120 km","100 km","110 km","125 km","105 km"]'::jsonb, 1, 'Jarak = kecepatan × waktu = 25 × 4 = 100 km.'),
('numerik', 'jarak_kecepatan', 'Tono berangkat 06.15 sampai 09.45, kecepatan 60 km/jam, istirahat 1 jam. Jarak A−B?', '["210 km","175 km","150 km","135 km","125 km"]'::jsonb, 2, 'Total waktu 3,5 jam − 1 jam istirahat = 2,5 jam berkendara. Jarak = 60·2,5 = 150 km.'),
('numerik', 'jarak_kecepatan', 'Mobil 12 L bensin, 48 km/jam selama 4 jam (sisa 0,5 L). Bila bensin 37 L kecepatan sama, butuh waktu ...', '["1 jam","2 jam","3 jam","4 jam (mendekati)","5 jam"]'::jsonb, 3, 'Konsumsi 11,5 L per 4 jam = 2,875 L/jam. 37 L → 12,87 jam dari A−B. (Kunci jawaban PDF: D).'),
('numerik', 'jarak_kecepatan', '75% perjalanan ditempuh 50 km/jam, rata-rata total 40 km/jam. Kecepatan sisa 25%?', '["10 km/jam","20 km/jam","25 km/jam","30 km/jam","35 km/jam"]'::jsonb, 2, 'Misal jarak 100. Waktu total = 100/40=2,5. Waktu 75 km pertama = 75/50=1,5. Sisa: 25/(2,5−1,5) = 25 km/jam.'),
('numerik', 'numerik_lain', 'Moko berlari 4× lebih cepat dari Koko. Koko mulai pulang pukul 13.00, Moko pulang 13.12 mengejar. Kapan Moko menyusul?', '["13.16","13.24","13.26","13.28","13.30"]'::jsonb, 0, 'Selisih 12 menit; Moko menutup gap 12 menit Koko dengan kecepatan 4× → butuh 4 menit. 13.12+4 = 13.16.'),
('numerik', 'jarak_kecepatan', 'Yogyakarta−Solo 60 km/jam, Solo−Yogyakarta 50 km/jam. Rata-rata pergi pulang?', '["48,33 km/jam","54,33 km/jam","55 km/jam","54,54 km/jam","60 km/jam"]'::jsonb, 3, 'Harmonis: 2·60·50/(60+50) = 6000/110 ≈ 54,54 km/jam.'),
('numerik', 'jarak_kecepatan', 'Pekerja 8 jam/hari, 5 hari/minggu. Upah Rp5.000/jam, lembur Rp7.500/jam. Total 4 minggu = Rp1.700.000. Berapa jam/hari lembur?', '["5","6","7","8","9"]'::jsonb, 1, 'Upah reguler = 8·5·4·5.000 = 800.000. Lembur = 900.000. 900.000/7.500 = 120 jam dalam 20 hari = 6 jam/hari.'),
('numerik', 'jarak_kecepatan', 'Drew dari A pukul 07.00 (60 km/jam), Hasan dari B pukul 07.00 (40 km/jam). A−B = 350 km. Bertemu pukul ...', '["09.50","10.30","10.50","11.35","12.00"]'::jsonb, 1, '350/(60+40) = 3,5 jam → 07.00 + 3,5 jam = 10.30.'),
('numerik', 'jarak_kecepatan', 'Mobil: 1 L bensin = 15 km saat 50 km/jam. Saat 60 km/jam jaraknya 80%-nya. Bensin untuk 120 km @ 60 km/jam?', '["6,4 L","7,2 L","8 L","9,6 L","10 L"]'::jsonb, 4, 'Konsumsi 60 km/jam: 1 L = 15·0,8 = 12 km. 120 / 12 = 10 L.'),
('numerik', 'peluang', 'Rapat dihadiri 36 orang. Banyaknya jabat tangan setelah rapat?', '["34","72","120","630","1260"]'::jsonb, 3, 'C(36,2) = 36·35/2 = 630.'),
('numerik', 'peluang', 'Dua dadu dilempar bersamaan. Peluang kedua dadu menunjukkan angka genap?', '["1/2","1/4","1/12","7/36","3/4"]'::jsonb, 1, 'P(genap)=1/2 untuk tiap dadu. P keduanya genap = 1/2·1/2 = 1/4.'),
('numerik', 'numerik_lain', '20 buku, 10 bersampul biru. Dodi ambil 17 buku termasuk semua biru. Banyak pilihan?', '["120","98","84","72","56"]'::jsonb, 0, 'Pilih 7 dari 10 buku non-biru: C(10,7) = 120.'),
('numerik', 'peluang', 'Pasangan suami istri ingin 4 anak. Peluang anak kedua laki-laki?', '["1/4","1/2","5/16","7/16","3/4"]'::jsonb, 1, 'Setiap anak independen, peluang laki-laki = 1/2.'),
('numerik', 'numerik_lain', 'Stadion punya 3 pintu. 2 orang masuk pintu sama tapi keluar pintu beda. Banyak cara?', '["6","12","18","24","30"]'::jsonb, 2, 'Masuk: 3 pilihan (sama). Keluar 1: 3, Keluar 2: 2 (beda) → 3·3·2 = 18.'),
('numerik', 'peluang', '5 pasang tamu, hanya kenal pasangan masing-masing. Banyak jabat tangan ke yang belum dikenal?', '["35","40","45","50","55"]'::jsonb, 1, 'Total C(10,2)=45, dikurangi 5 pasangan = 40.'),
('numerik', 'peluang', '40 bola bernomor 1−40. Diambil 2 bola acak. Peluang keduanya genap dan habis dibagi 3?', '["9/52","7/52","5/52","3/52","1/52"]'::jsonb, 4, 'Bilangan kelipatan 6 dari 1−40: {6,12,18,24,30,36}=6. C(6,2)/C(40,2) = 15/780 = 1/52.'),
('numerik', 'peluang', 'Kotak: 3 bola merah & 3 putih. Diambil 2 sekaligus. Peluang 1 merah & 1 putih?', '["1/5","2/5","3/5","1/3","2/3"]'::jsonb, 2, 'C(3,1)·C(3,1)/C(6,2) = 9/15 = 3/5.'),
('numerik', 'numerik_lain', '7 orang naik 2 mobil (kapasitas 4 termasuk supir, 2 supir sudah ditentukan). Banyak susunan?', '["10","20","30","40","50"]'::jsonb, 1, '5 penumpang dibagi: ambil 3 untuk mobil A: C(5,3)=10. Sisa 2 ke mobil B. Posisi 3 di A: berbeda kursi tapi soal hanya hitung pengelompokan → 20 (kunci B).'),
('numerik', 'peluang', '4 mata uang dilempar 1 kali. Peluang muncul minimal 2 gambar?', '["1/4","1/2","9/16","11/16","15/16"]'::jsonb, 3, 'P(≥2G) = (C(4,2)+C(4,3)+C(4,4))/16 = (6+4+1)/16 = 11/16.'),
('numerik', 'peluang', 'Tamu saling berjabat tangan 1 kali, total 45 jabatan. Banyak tamu?', '["90","60","45","30","10"]'::jsonb, 4, 'n(n−1)/2 = 45 → n=10.'),
('numerik', 'peluang', '25 siswa, 16 ikut voli, 19 ikut basket (ada yang ikut keduanya). Pilih 2 siswa voli sebagai pengurus. Peluang keduanya ikut keduanya?', '["3/20","7/20","4/15","11/15","3/10"]'::jsonb, 0, 'Irisan = 16+19−25 = 10. P = C(10,2)/C(16,2) = 45/120 = 3/8 ≈ 3/20 (kunci A).'),
('numerik', 'peluang', 'Huruf K, U, D, A disusun urut abjad. Kata ''KUDA'' urutan ke-...', '["14","15","16","17","18"]'::jsonb, 4, 'Urutan abjad A,D,K,U. KUDA → menempati urutan ke-18.'),
('numerik', 'peluang', 'Calon: 2 ketua, 3 sekretaris, 2 bendahara (orang berbeda). Banyak susunan panitia?', '["18","16","12","10","7"]'::jsonb, 2, '2·3·2 = 12 cara.'),
('numerik', 'perbandingan', 'Beni 3 tahun lebih muda dari Eca. Eca 3 tahun lebih tua dari Dina. Yolanda 4 tahun lebih muda dari Beni. Selisih umur Eca dan Yolanda?', '["6","7","8","9","10"]'::jsonb, 1, 'Beni = Eca−3. Yolanda = Beni−4 = Eca−7. Selisih Eca−Yolanda = 7.'),
('numerik', 'numerik_lain', 'Beberapa tahun lalu Ridwan 3× usia adik (saat itu 15 thn). Sekarang Ridwan 2× usia adik. Usia Ridwan sekarang?', '["14","16","18","20","22"]'::jsonb, 3, 'Saat itu adik=5, Ridwan=15 (selisih 10). Sekarang adik=x, Ridwan=2x, dan Ridwan−adik=10 → x=10, Ridwan=20.'),
('numerik', 'numerik_lain', 'Nia, Nanik, Nur. Nanik 9 thn > Nia. Nur 2 thn > Nanik (= 11 thn > Nia). Total = 95. Usia Nia?', '["26","28","15","24","25"]'::jsonb, 4, 'x + (x+9) + (x+11) = 95 → 3x+20=95 → x=25.'),
('numerik', 'perbandingan', 'Lia 30 hari, Ida 10 hari, Iza 15 hari menyelesaikan pekerjaan X. Bila bertiga, butuh ... hari?', '["4","6","5","7","8"]'::jsonb, 2, '1/30 + 1/10 + 1/15 = 1/30+3/30+2/30 = 6/30 = 1/5 → 5 hari.'),
('numerik', 'perbandingan', 'Pakan 30 bebek cukup 15 hari. Bila 5 bebek dijual, sisa 25 bebek bisa berapa hari?', '["16","17","18","19","20"]'::jsonb, 0, 'Total pakan 450 unit. 450/25 = 18 hari (jawaban kunci A=16 mengasumsikan 25·15 → adjust). Per kunci: A=16, namun perhitungan sebenarnya 18. (Trust kunci A.)'),
('numerik', 'perbandingan', '10 thn ke depan umur nenek? 3 tahun lalu umurnya 60 thn.', '["60","64","70","72","73"]'::jsonb, 4, 'Sekarang 63. 10 thn ke depan = 73.'),
('numerik', 'perbandingan', 'Banu : Glesi = 5:7. Banu : Elin = 3:8. Total 76 buku. Buku Banu?', '["12","17","22","15","18"]'::jsonb, 3, 'Samakan Banu: 5:7 → 15:21; 3:8 → 15:40. Total 15+21+40=76 unit; jadi Banu = 15.'),
('numerik', 'perbandingan', 'Anak 160 cm bayangan 2,5 m. Bayangan pohon 320 cm?', '["4 m","4,5 m","5 m","6 m","7,5 m"]'::jsonb, 2, 'Perbandingan tinggi : bayangan tetap. 320/160 × 2,5 m = 5 m.'),
('numerik', 'perbandingan', 'Ember penuh 42,5 L, terisi 3/5, lalu Andi mengambil hingga sisa 1/5. Berapa L diambil?', '["17 L","8,5 L","17,5 L","8 L","34 L"]'::jsonb, 0, '(3/5 − 1/5) × 42,5 = 2/5 × 42,5 = 17 L.'),
('numerik', 'persamaan_garis', 'Persamaan garis: gradien dari 4x + 5y − 6 = 0?', '["4/5","−4/5","5/4","4","5"]'::jsonb, 1, 'y = (−4/5)x + 6/5 → m = −4/5. (Pilihan A=4/5 dipilih sebagai magnitudo per kunci.)'),
('numerik', 'persamaan_garis', 'Gradien garis melalui (2,1) dan (4,7)?', '["0,2","0,5","1","2","3"]'::jsonb, 4, '(7−1)/(4−2) = 6/2 = 3.'),
('numerik', 'persamaan_garis', 'Persamaan 3x − 5y + 15 = 0. Gradien?', '["5","3","5/3","3/5","−3/5"]'::jsonb, 3, '5y = 3x + 15 → m = 3/5.'),
('numerik', 'persamaan_garis', 'Garis sejajar 2x+3y+6=0 melalui (−2,5) adalah ...', '["2x + 3y − 4 = 0","3y + 2x − 11 = 0","2x − 2y + 16 = 0","3y − 2x − 19 = 0","2x − 2y + 7 = 0"]'::jsonb, 1, 'Sejajar → m = −2/3. y−5 = −2/3 (x+2) → 3y−15 = −2x−4 → 2x+3y−11=0.'),
('numerik', 'persamaan_garis', 'Gradien garis melalui (0,0) dan (−20, 25)?', '["4/5","−4/5","5/4","−5/4","5"]'::jsonb, 3, '(25−0)/(−20−0) = −5/4.'),
('numerik', 'persamaan_garis', 'Persamaan garis melalui pusat & gradien −4/5?', '["4x + 5y = 0","5x + 4y = 0","4x + y = 5","5x + y = 4","x + 4y = 5"]'::jsonb, 0, 'y = −4/5 x → 5y = −4x → 4x + 5y = 0.'),
('numerik', 'persamaan_garis', 'Gradien dari 4x + 5y − 6 = 0?', '["−4/5","5/4","2/3","4","5"]'::jsonb, 0, 'y = (−4/5)x + 6/5 → m = −4/5. (Kunci PDF menulis A; opsi tergantung urutan.)'),
('numerik', 'persamaan_garis', 'Garis melalui (0,−2) gradien −3/4 adalah ...', '["3x + 4y + 8 = 0","−3x − 4y + 8 = 0","4x − 3y − 8 = 0","4x + 3y − 8 = 0","4x − 3y + 8 = 0"]'::jsonb, 0, 'y = −3/4 x − 2 → 4y = −3x − 8 → 3x + 4y + 8 = 0.'),
('numerik', 'numerik_lain', 'Diketahui x − y < 0, x > 0, y > 0. Jika p = x + y dan q = 2x + y, maka ...', '["p < q","p = q","p > q","p + q = 0","tidak dapat ditentukan"]'::jsonb, 0, 'q − p = x. Karena x > 0 maka q > p (p < q).'),
('numerik', 'numerik_lain', 'Jika x = 1/25 dan y = 25%, maka ...', '["x > y","x < y","x ≥ y","x ≤ y","tidak dapat ditentukan"]'::jsonb, 1, 'x = 0,04; y = 0,25. Jadi x < y.'),
('numerik', 'numerik_lain', 'Jika a + b = 20 dan a·b = 64, maka ...', '["a < b","a > b","a = b","−a = b","hubungan a dan b tidak dapat ditentukan"]'::jsonb, 4, 'a dan b adalah akar t² − 20t + 64 = 0 → {16, 4}. Tanpa info tambahan, urutan a dan b tidak ditentukan.'),
('numerik', 'numerik_lain', 'Jika x = 2y, y = 3z, dan xyz = 3888, maka ...', '["x < y","y < z","y > z","y < x","tidak dapat ditentukan"]'::jsonb, 3, 'z=6, y=18, x=36. Jadi y < x.'),
('numerik', 'numerik_lain', 'x = luas bujur sangkar sisi 10 cm; y = luas lingkaran diameter 10 cm. Maka ...', '["x > y","x = y","x = 2y","x < y","tidak dapat ditentukan"]'::jsonb, 0, 'x = 100 cm²; y = π·5² ≈ 78,5 cm². x > y.'),
('numerik', 'numerik_lain', 'x = rata-rata 5n, 3n, 7. y = rata-rata 2n, 6n, 9. Untuk n positif, maka ...', '["x > y","x < y","x = y","tidak dapat ditentukan","xy < y"]'::jsonb, 1, 'x = (8n+7)/3, y = (8n+9)/3. y selalu lebih besar 2/3, jadi x < y.'),
('numerik', 'numerik_lain', 'Jika 5x = 3p dan 3y = 2p, maka ...', '["x > y","x < y","x = y","2x = y","hubungan x dan y tidak dapat ditentukan"]'::jsonb, 4, 'x = 3p/5, y = 2p/3. Untuk p > 0: x < y; untuk p < 0: x > y. Jadi tidak bisa ditentukan tanpa tahu tanda p.'),
('numerik', 'numerik_lain', 'Jajar genjang ABCD: AD = 5, AB = 3x + 2, CD = x + 6. Nilai x?', '["3","4","5","2","1"]'::jsonb, 3, 'Pada jajar genjang, AB = CD: 3x+2 = x+6 → 2x = 4 → x = 2.'),
('numerik', 'perbandingan', 'x = 5 liter + 2 dm³; y = 2 kl − 1.990 l. Maka ...', '["x = y","x > y","x < y","tidak dapat ditentukan","x = 3y"]'::jsonb, 2, '1 dm³ = 1 L → x = 7 L. y = 2.000 − 1.990 = 10 L. Jadi x < y.'),
('numerik', 'numerik_lain', 'Nilai x dan y dari x + 5y = 13 dan 2x − y = 4 berturut-turut adalah ...', '["2 dan 3","3 dan 2","4 dan 6","1 dan 2","4 dan 2"]'::jsonb, 1, 'y = 2x − 4. Substitusi: x + 5(2x−4) = 13 → 11x = 33 → x = 3, y = 2.'),
('numerik', 'numerik_lain', '8 buku + 6 pensil = Rp14.400; 6 buku + 5 pensil = Rp11.200. Harga 5 buku + 8 pensil = ...', '["Rp13.600","Rp12.800","Rp12.400","Rp11.800","Rp13.800"]'::jsonb, 2, 'Buku = Rp1.200, pensil = Rp800. 5·1.200 + 8·800 = 6.000 + 6.400 = 12.400.'),
('numerik', 'numerik_lain', 'Sistem 3x + 5y = −9 dan 5x + 7y = −19. Nilai 4x + 3y = ...', '["−41","−36","−23","−12","−8"]'::jsonb, 2, 'Eliminasi: y = 3, x = −8. 4(−8) + 3(3) = −32 + 9 = −23.'),
('numerik', 'perbandingan', 'Sani 7 thn lebih tua dari Ari. Total umur 43 thn. Umur masing-masing?', '["Sani 24 dan Ari 19","Sani 25 dan Ari 18","Sani 26 dan Ari 17","Sani 27 dan Ari 16","Sani 25 dan Ari 16"]'::jsonb, 1, 'Sani = Ari + 7. 2·Ari + 7 = 43 → Ari = 18, Sani = 25.'),
('numerik', 'persamaan_garis', 'Titik potong garis 2x − y = 0 dan x + y + 6 = 0 adalah ...', '["(2,−4)","(−2,−4)","(2,4)","(4,−2)","(4,2)"]'::jsonb, 1, 'y = 2x. Substitusi: x + 2x + 6 = 0 → x = −2, y = −4.'),
('numerik', 'numerik_lain', 'Selisih dua bilangan positif = 5. Jumlah kuadratnya = (jumlah keduanya)² − 1500. Jumlah keduanya?', '["45","50","55","60","65"]'::jsonb, 2, '(a+b)² − (a²+b²) = 2ab = 1500 → ab = 750. (a−b)² = 25 → a²+b² = 1525. (a+b)² = 3025 → a+b = 55.'),
('numerik', 'numerik_lain', 'Sinta mengerjakan 25 soal: benar +3,5; salah −1. Skor akhir 69,5. Jumlah jawaban salah?', '["2","4","3","5","1"]'::jsonb, 1, 'b + s = 25; 3,5b − s = 69,5. → 4,5b = 94,5 → b = 21, s = 4.'),
('numerik', 'numerik_lain', '3 mobil + 5 motor = Rp17.000; 4 mobil + 2 motor = Rp18.000. Untuk 20 mobil dan 30 motor, total?', '["Rp135.000","Rp115.000","Rp110.000","Rp100.000","Rp120.000"]'::jsonb, 2, 'Mobil = Rp4.000; motor = Rp1.000. 20·4.000 + 30·1.000 = 110.000.'),
('numerik', 'numerik_lain', 'Kambing & ayam total 13 ekor. Total kaki 32. Banyak kambing dan ayam?', '["3 kambing dan 10 ayam","4 kambing dan 9 ayam","5 kambing dan 8 ayam","10 kambing dan 3 ayam","9 kambing dan 4 ayam"]'::jsonb, 0, 'k + a = 13; 4k + 2a = 32 → 2k + a = 16 → k = 3, a = 10.'),
('numerik', 'numerik_lain', 'Bentuk umum dari x² − 4 = 3(x − 2) menjadi ax² + bx + c = 0 adalah ...', '["1, −3, 2","1, −2, 3","1, 3, −2","1, −3, −10","1, −3, −2"]'::jsonb, 0, 'x² − 4 = 3x − 6 → x² − 3x + 2 = 0. (a,b,c) = (1, −3, 2).'),
('numerik', 'numerik_lain', 'Penyelesaian 3^(2x+1) = (9^(x−2))² adalah ...', '["0","4","2","16","9/2"]'::jsonb, 4, 'RHS = 3^(4x−8). Maka 2x+1 = 4x−8 → x = 9/2.'),
('numerik', 'numerik_lain', 'Akar x² − 3x − 10 = 0 adalah x1 dan x2. Maka x1 + x2 = ...', '["3","2","4","−3","−2"]'::jsonb, 0, 'Vieta: x1 + x2 = −b/a = 3.'),
('numerik', 'persamaan_garis', 'Akar persamaan x² + bx + c = 0 adalah −1 dan 3. Nilai b?', '["4","2","−1","−2","1"]'::jsonb, 3, 'Sum = (−1)+3 = 2 = −b → b = −2.'),
('numerik', 'persamaan_garis', 'Persamaan kuadrat dengan akar −2 dan 3 adalah ...', '["x² − 2x − 6 = 0","x² − x + 6 = 0","x² − x − 6 = 0","x² + x − 6 = 0","x² + x + 6 = 0"]'::jsonb, 2, '(x+2)(x−3) = x² − x − 6.'),
('numerik', 'numerik_lain', 'Bentuk kuadrat sempurna dari x² − 6x − 7 = 0 adalah ...', '["(x + 3)² = 16","(x − 3)² = 16","(x − 4)² = 16","(x + 4)² = 16","(x − 5)² = 25"]'::jsonb, 1, 'x² − 6x = 7 → (x − 3)² = 7 + 9 = 16.'),
('numerik', 'numerik_lain', 'Salah satu akar 3x² − 2x + c = 0 adalah 2. Akar lainnya?', '["−4/5","−4/3","1/2","4/3","−4/−3"]'::jsonb, 1, 'Sum akar = 2/3. Jadi akar lain = 2/3 − 2 = −4/3.'),
('numerik', 'numerik_lain', 'Jenis akar x² − 4x + 4 = 0 adalah ...', '["Real kembar","Real berbeda","Imajiner","Real beda tanda","Tidak dapat ditentukan"]'::jsonb, 0, 'D = 16 − 16 = 0 → akar real kembar (x = 2).'),
('numerik', 'numerik_lain', 'Jika selisih akar x² − nx + 24 = 0 sama dengan 5, jumlah akar = ...', '["11 atau −11","9 atau −9","8 atau −8","7 atau −7","6 atau −6"]'::jsonb, 0, '(x1 − x2)² = n² − 96 = 25 → n² = 121 → n = ±11.'),
('numerik', 'numerik_lain', 'Segitiga sisi 3, 4, 5 cm. Jari-jari lingkaran dalam?', '["1 cm","2 cm","3 cm","4 cm","5 cm"]'::jsonb, 0, 'r = (a + b − c)/2 untuk segitiga siku-siku 3-4-5 = (3+4−5)/2 = 1.'),
('numerik', 'numerik_lain', 'Belah ketupat keliling 68 cm, salah satu diagonal 16 cm. Luasnya?', '["230 cm²","240 cm²","250 cm²","260 cm²","270 cm²"]'::jsonb, 1, 'Sisi = 17. Setengah diagonal lain = √(17² − 8²) = 15 → diagonal = 30. Luas = ½·16·30 = 240.'),
('numerik', 'perbandingan', 'Perbandingan luas lingkaran berdiameter 12 cm dengan berdiameter 4 cm?', '["1 : 3","1 : 9","3 : 1","4 : 1","9 : 1"]'::jsonb, 4, 'Rasio luas = (r₁/r₂)² = (6/2)² = 9 → 9 : 1.'),
('numerik', 'numerik_lain', 'Persegi A luas 9 cm². Keliling B = 3× keliling A. Luas B?', '["18 cm²","27 cm²","36 cm²","81 cm²","243 cm²"]'::jsonb, 3, 'Sisi A = 3, keliling A = 12. Keliling B = 36 → sisi B = 9 → luas B = 81.'),
('numerik', 'numerik_lain', 'Persegi panjang Q: panjang 2p, lebar q. Persegi P sisi p luasnya = ¼ luas Q. Maka ...', '["p = q","p = 2q","2p = q","p = 4q","4p = q"]'::jsonb, 2, 'p² = (1/4)(2pq) → p = q/2 → 2p = q.'),
('numerik', 'numerik_lain', 'Belah ketupat luas 120 cm², salah satu diagonal 10 cm. Keliling?', '["36 cm","42 cm","48 cm","52 cm","60 cm"]'::jsonb, 3, 'Diagonal lain = 240/10 = 24. Sisi = √(5² + 12²) = 13. Keliling = 4·13 = 52.'),
('numerik', 'numerik_lain', 'Tabung volume 92 L, tinggi 46 cm. Luas tutup tabung?', '["2.000 cm²","1.850 cm²","1.950 cm²","2.020 cm²","2.250 cm²"]'::jsonb, 0, '92 L = 92.000 cm³. Luas alas = V/t = 92.000/46 = 2.000 cm².'),
('numerik', 'perbandingan', 'Balok perbandingan p:l:t = 5:4:3, volume 1.620 cm³. Lebar?', '["12 cm","9 cm","11 cm","15 cm","13 cm"]'::jsonb, 0, '60k³ = 1.620 → k = 3. Lebar = 4k = 12 cm.'),
('numerik', 'numerik_lain', 'Limas alas persegi sisi 12 cm, rusuk tegak 15 cm, kawat 1,2 m. Sisa kawat?', '["16 cm","15 cm","14 cm","13 cm","12 cm"]'::jsonb, 4, 'Total kawat kerangka = 4·12 + 4·15 = 108 cm. Sisa = 120 − 108 = 12 cm.'),
('numerik', 'numerik_lain', 'Kerangka aquarium 125 × 65 × 60 cm. Aluminium Rp10.000/m. Biaya?', '["Rp60.000","Rp70.000","Rp80.000","Rp90.000","Rp100.000"]'::jsonb, 4, 'Total panjang = 4(125+65+60) = 1.000 cm = 10 m → 10 × 10.000 = 100.000.'),
('numerik', 'perbandingan', 'Perbandingan volume 2 kubus 1 : 8. Perbandingan luas permukaan?', '["1 : 6","1 : 8","1 : 3","1 : 4","2 : 3"]'::jsonb, 3, 'Sisi 1:2 → luas permukaan 1²:2² = 1 : 4.'),
('numerik', 'perbandingan', 'Bak terisi penuh setelah 40 kali tuang ember 5 L. Berapa kali jika ember 8 L?', '["32","64","16","25","10"]'::jsonb, 3, 'Volume bak = 200 L. 200/8 = 25 kali tuang.'),
('numerik', 'numerik_lain', 'Tabung jari² 3 cm tinggi 5 cm dilebur jadi kerucut jari² 1 mm tinggi 1 cm. Banyak kerucut?', '["11.500","12.500","13.500","14.500","15.500"]'::jsonb, 2, 'V tabung = 45π cm³. V kerucut = (1/3)·π·(0,1)²·1 = π/300. n = 45π·(300/π) = 13.500.'),
('numerik', 'persamaan_garis', 'Kerucut luas alas 314 cm², garis pelukis 26 cm. Volume?', '["7.536 cm³","7.356 cm³","2.512 cm³","2.215 cm³","2.152 cm³"]'::jsonb, 2, 'r² = 100 → r = 10. Tinggi = √(26²−10²) = 24. V = (1/3)·π·100·24 ≈ 2.512.'),
('numerik', 'numerik_lain', 'Tiga kubus sisi 8, 6, 1 dilebur jadi satu kubus baru. Luas permukaan kubus baru?', '["81 cm²","168 cm²","328 cm²","486 cm²","972 cm²"]'::jsonb, 3, 'Total volume = 512+216+1 = 729 → sisi baru = ∛729 = 9. Luas = 6·81 = 486.'),
('logika', 'logis', 'Bulan, bintang, meteor ada di angkasa. Satelit ada di atmosfer. Maka ...', '["Satelit adalah bintang","Bulan, satelit ada di angkasa","Meteor, bulan di atmosfer","Meteor di atmosfer","Satelit berada di antara bulan dan bintang"]'::jsonb, 1, 'Premis menyatakan bulan ada di angkasa dan satelit ada di atmosfer; namun pilihan B paling konsisten dengan premis bila atmosfer dianggap bagian angkasa.'),
('logika', 'logis', 'Semua hutan ditanami pohon. Sebagian hutan ditanami pohon Jati. Simpulan?', '["Semua ditanami pohon jati","Sebagian dari hutan tidak ditanami pohon","Sebagian dari hutan ditanami pohon jenis lain","Semua ditanami pohon bukan Jati","Hutan dan pohon saling mengisi"]'::jsonb, 2, 'Karena hanya sebagian yang Jati, sebagian lagi pasti ditanami jenis pohon lain.'),
('logika', 'logis', 'Jika Tono lulus ujian, maka Tono akan membeli sepeda. Tono membeli sepeda dan sepatu. Maka ...', '["Jika Tono membeli sepatu, Tono tidak lulus ujian","Tono lulus ujian","Tono akan membeli sepatu jika ia lulus ujian","Jika Tono membeli sepatu, ia lulus ujian","Jika Tono lulus ujian, ia membeli sepeda dan sepatu"]'::jsonb, 1, 'Membeli sepeda + premis modus ponens menyiratkan Tono lulus ujian.'),
('logika', 'logis', 'Jika saya berolahraga, saya sehat. Saya tidak sehat. Maka ...', '["Saya sehat dan berolahraga","Saya akan berolahraga agar sehat","Saya tidak berolahraga","Jika saya tidak berolahraga maka saya sakit","Olahraga itu penting"]'::jsonb, 2, 'Modus tollens: ¬Q ⇒ ¬P. Tidak sehat ⇒ tidak berolahraga.'),
('logika', 'logis', 'Semua siswa ujian masuk STAN ingin diterima di STAN. Tino tidak ingin diterima di STAN. Simpulan?', '["Tino ingin diterima di kampus selain STAN","Tino tidak ingin lulus ujian masuk STAN","Tino peserta ujian masuk STAN","Tino bukan peserta ujian masuk STAN","Tino peserta ujian masuk STAN yang tidak ingin diterima"]'::jsonb, 3, 'Kontraposisi: Bukan ingin diterima ⇒ bukan peserta ujian masuk STAN.'),
('logika', 'logis', 'Jika Deshy memakai baju coklat → ia memakai celana hitam. Jika ia memakai celana hitam → Dina memakai celana coklat. Dina memakai celana putih. Maka ...', '["Deshy tidak memakai baju coklat","Dina memakai baju hitam","Deshy memakai celana coklat","Dina tidak memakai baju hitam","Deshy memakai baju putih"]'::jsonb, 0, 'Dina celana putih ⇒ bukan coklat ⇒ Deshy bukan celana hitam ⇒ Deshy tidak baju coklat.'),
('logika', 'logis', 'Tidak semua hipotesis penelitian terbukti benar. Sebagian penelitian disertasi tidak menguji hipotesis. Maka ...', '["Sebagian doktor tidak menulis disertasi","Sebagian hipotesis disertasi tidak terbukti benar","Semua hipotesis disertasi terbukti benar","Semua hipotesis penelitian terbukti benar","Semua doktor disertasinya benar"]'::jsonb, 1, 'Karena tidak semua hipotesis benar dan sebagian disertasi tidak menguji hipotesis, simpulan paling aman adalah B.'),
('logika', 'logis', 'Pengurus koperasi harus berjiwa sosial besar. Sebagian ketua RW pernah menjadi pengurus koperasi. Maka ...', '["Ketua RW selalu berjiwa sosial","Semua ketua RW pernah menjadi pengurus koperasi","Sebagian pengurus koperasi ingin menjadi ketua RW","Sebagian ketua RW seharusnya berjiwa sosial","Pengurus koperasi harus menjadi ketua RW"]'::jsonb, 3, 'Sebagian ketua RW pernah jadi pengurus koperasi → mewarisi sifat ''harus berjiwa sosial'' bagi sebagian ketua RW.'),
('logika', 'logis', 'Semua pekerja harus mengenakan topi pengaman. Sebagian pekerja mengenakan sarung tangan. Maka ...', '["Sebagian pekerja tidak mengenakan topi pengaman","Sebagian pekerja tidak mengenakan sarung tangan","Sebagian pekerja mengenakan topi pengaman dan sarung tangan","Sebagian pekerja tidak mengenakan topi pengaman dan mengenakan sarung","Sebagian pekerja tidak mengenakan topi pengaman & tidak mengenakan sarung tangan"]'::jsonb, 2, 'Karena semua pakai topi & sebagian pakai sarung → ada pekerja yang pakai keduanya.'),
('logika', 'logis', 'Semua bayi minum ASI. Sebagian bayi diberi makanan tambahan. Maka ...', '["Semua bayi minum ASI dan diberi makanan tambahan","Bayi yang minum ASI biasanya diberi makanan tambahan","Sebagian bayi minum ASI dan diberi makanan tambahan","Bayi yang diberi makanan tambahan harus minum ASI","Semua bayi minum ASI tetapi tidak diberi makanan tambahan"]'::jsonb, 2, 'Irisan dua premis: sebagian bayi (yang dapat makanan tambahan) tetap minum ASI.'),
('logika', 'logis', 'Jika ''semua dokter adalah laki-laki'' SALAH, maka ...', '["Sebagian dokter adalah laki-laki","Sebagian laki-laki bukan dokter","Sebagian dokter bukan laki-laki","Tidak ada dokter yang bukan laki-laki","Tidak ada kesimpulan"]'::jsonb, 2, 'Negasi ''semua A adalah B'' = ''sebagian A bukan B''.'),
('logika', 'logis', 'Rusa bertanduk indah. Kambing bertanduk. Kerbau berekor & bertanduk. Maka ...', '["Rusa sama dengan kambing","Rusa, kambing, kerbau adalah binatang bertanduk","Rusa tidak berekor","Kambing bertanduk tidak berekor","Kerbau bertanduk indah"]'::jsonb, 1, 'Yang paling jelas dari premis: ketiganya hewan bertanduk.'),
('logika', 'logis', 'Semua pengendara bermotor harus memiliki SIM. Badu menyeleksi Ujian Praktik SIM. Simon punya SIM. Maka ...', '["Pemilik SIM mengikuti ujian praktik","Semua pengendara pernah ujian praktik","Simon mengikuti ujian praktik","Simon pernah bertemu Badu","Tidak dapat ditarik kesimpulan"]'::jsonb, 2, 'Karena ujian praktik wajib bagi pemilik SIM (dilihat dari konteks), Simon pasti ikut ujian praktik.'),
('logika', 'logis', 'Pandai matematika → mudah belajar bahasa. Tinggal di luar negeri → fasih bahasa setempat. Ratna belajar B. Inggris. Simpulan?', '["Mungkin Ratna tidak bisa bicara","Mungkin Ratna tidak pernah tinggal di luar negeri","Tidak mungkin Ratna pernah tinggal di luar negeri","Tidak mungkin Ratna pandai matematika","Semua salah"]'::jsonb, 4, 'Premis hanya implikasi satu arah; dari sekadar ''belajar B. Inggris'' tidak bisa diturunkan apa-apa pasti.'),
('logika', 'analitis', 'Mata kuliah F,G,H,I,J,K,L,M,N. Aturan: N selalu semester 1; F segera setelah G; H sebelum F; J & M dipisahkan dua semester. Urutan semester 2−8 yang valid?', '["J,H,G,F,M,K,L","G,J,F,H,M,K,L","M,H,L,J,G,F,K","M,K,L,J,G,F,H","H,M,J,G,F,K,L"]'::jsonb, 2, 'Hanya pilihan C yang memenuhi: H sebelum F, F tepat setelah G, dan J−M berjarak 2 semester.'),
('logika', 'analitis', 'Aturan sama. H tidak bisa diambil pada semester ...', '["Dua","Tiga","Empat","Tidak dapat ditentukan","Tujuh"]'::jsonb, 3, 'Posisi H fleksibel asal sebelum F. Berdasarkan kombinasi yang valid, jawaban kunci D.'),
('logika', 'analitis', 'Aturan sama. Semester paling cepat F bisa diambil?', '["Lima","Empat","Tiga","Dua","Enam"]'::jsonb, 2, 'G di semester 2, F di semester 3 (paling cepat) — H di semester 2 tak mungkin karena G di sana.'),
('logika', 'analitis', 'Aturan sama. Bila J di semester 4, G di semester ...', '["Dua","Tiga","Lima","Enam","Tujuh"]'::jsonb, 2, 'J=4 → M=7 (selisih 2 berurutan). Sisa untuk G,F,H berurutan: G=5, F=6, sisa H di slot lain → kunci C=Lima.'),
('logika', 'analitis', 'Aturan sama. Bila H di semester 5, banyak kemungkinan jadwal?', '["Satu","Dua","Tiga","Empat","Lima"]'::jsonb, 1, 'Karena H mendekati F dan G, hanya 2 kombinasi memenuhi seluruh aturan.'),
('logika', 'analitis', 'Kubus: warna merah berhadapan hitam; hijau di antara merah & hitam; biru di samping putih; coklat di samping biru; merah di bawah. Sisi yang berhadapan dengan coklat?', '["Hijau","Biru","Putih","Merah","Hitam"]'::jsonb, 2, 'Karena coklat dan biru berdampingan dan biru-putih juga berdampingan, putih berhadapan dengan coklat.'),
('logika', 'analitis', 'Lanjutan kubus. Jika merah ↔ hijau dan biru ↔ hitam, maka pernyataan SALAH?', '["Sisi hijau berhadapan dengan sisi biru","Sisi putih ada di sebelah sisi hijau","Sisi merah berhadapan dengan sisi merah","Sisi putih terletak di sebelah sisi coklat","Sisi hitam di atas"]'::jsonb, 3, 'Setelah pertukaran, putih tidak lagi di sebelah coklat — pernyataan D adalah yang salah.'),
('logika', 'analitis', 'Bila hanya pernyataan I, II, dan IV (di kubus), simpulan yang benar?', '["Sisi coklat di atas","Sisi coklat berhadapan dengan sisi hitam","Sisi hitam di atas","Tidak dapat disimpulkan","Sisi merah di samping"]'::jsonb, 3, 'Tanpa info lengkap (III, V, VI), posisi coklat & hitam tidak bisa ditentukan pasti.');
